$ANSIBLE_VAULT;1.1;AES256
35326563343665613664373063626238643533343935626565616634373064643635626664633636
6339353639316530386336613035333832393338306433650a343135313561333133353262633234
35626431306536663230373132616666366265643633646431633038636136623831336565643434
6231373132323135350a663765653230613337393665306431313631346434656264303630363430
37613438343038623435613066313133633031653530353233643132313033356432343937656133
38646235336538373165366135616532666435323833336562326265643164313336626262326464
37326630643634653835613532656332353134366263346131393236376663363833653136356634
35383738616162623161303866323938316463373630366638386235393835326262353130326665
66343163636163336237653730643965303431343566313433626261643737356561623863326632
64623162623765393531323063383663613964343635306134383634666464663863646365353734
35343034643337313936313662356164613466646332633034393336353462373736643931356537
62656338646138616633353831316532313535383735623763366636336534373637363932303530
34353936663039356431633338623033663337326463363037643363386362663035386566643662
36353463313732396530623264643135363439353236623038616435646364316563653338646331
32313562343962663136393231396530373236616361376331303632316432353830336631616337
66623332313763653233333232643232386264666662326163326431306430313063353065653065
64636330626632656266303230393231386536643834346333643334636531666532623030393439
62616636633139633165626631343066363536366234366237663534383638346361616663383432
62353566646135396239343137346262653835656163663131623032366463316539633861303530
34386665623966353138303837363939306435323437346261653939376338633435326130366232
66643930373532393062326434316538653666376465303035653830376332333933
