---
all:
  vars:
    ansible_user: ansible # todo move to group vars?
  children:
    dev:
      hosts:
        dev.ffxiv.id:
          ansible_connection: ssh
    staging:
      hosts:
        staging.ffxiv.id:
          ansible_connection: ssh
    prod:
      hosts:
        ffxiv.id:
          ansible_connection: ssh
