---
all:
  children:
    dev:
      hosts:
        dev-host-1:
          ansible_connection: local
          validate_certs: false
          keycloak_url: https://id.ffxiv.local
          keycloak_ansible_client_id: ansible
          keycloak_realm_name: eorzea-dev
          keycloak_realm_display_name: Eorzea (DEV)
          keycloak_master_realm: master-dev
          passkey_relying_party_id: id.ffxiv.local

          clients:
          - client_id: alyx-discord
            client_credentials_flow: true
            jwks_url: https://alyx.discord.local/.well-known/jwks
    staging:
      hosts:
        staging-host-1:
          ansible_connection: local
          validate_certs: false
          keycloak_url: https://id.ffxiv.local
          keycloak_ansible_client_id: ansible
          keycloak_realm_name: eorzea-staging
          keycloak_realm_display_name: Eorzea (STAGING)
          keycloak_master_realm: master-staging
          passkey_relying_party_id: id.ffxiv.local
    prod:
      hosts:
        prod-host-1:
          ansible_connection: local
          validate_certs: false
          keycloak_url: https://id.ffxiv.local
          keycloak_ansible_client_id: ansible
          keycloak_realm_name: eorzea
          keycloak_realm_display_name: Eorzea
          passkey_relying_party_id: id.ffxiv.local
