---
all:
  children:
    dev:
      hosts:
        dev-host-1:
          ansible_connection: local
          validate_certs: false
          keycloak_url: https://id.ffxiv.local
          keycloak_ansible_client_id: ansible
          keycloak_realm_name: eorzea-dev
          keycloak_realm_display_name: Eorzea (DEV)
    staging:
      hosts:
        staging-host-1:
          ansible_connection: local
          validate_certs: false
          keycloak_url: https://id.ffxiv.local
          keycloak_ansible_client_id: ansible
          keycloak_realm_name: eorzea-staging
          keycloak_realm_display_name: Eorzea (STAGING)
    prod:
      hosts:
        prod-host-1:
          ansible_connection: local
          validate_certs: false
          keycloak_url: https://id.ffxiv.local
          keycloak_ansible_client_id: ansible
          keycloak_realm_name: eorzea
          keycloak_realm_display_name: Eorzea
          