$ANSIBLE_VAULT;1.1;AES256
65313861353333303263646333336666396234383238666630386564656538663165346438363263
6337393936646166363639343966363232306134353830380a666662333161626538336434666562
66646131323637383233626262643264653539666665663431363165326337313463306335316362
6334353265346565630a643362663463633932646435643233366536633332326132636234383366
30376133653035323061303664653661333634366634303032336464666430396635353266326433
30623434363765323135383865386565343839613838313862663030333330343663336131626662
31653664313339663565306232636133656435333962386339643864323161353234626464613661
62393830363934656131386138313430316639313263363436336334316238376561306134316465
39363864663931353962306563343065666138336565393266663036343035383633336361616430
33353638636137383133376330643631313839353064643863636439363335613530343664316162
32383066616632353239393062323936643031653062623832633262636166356361633330613263
61666634333864623138333062383433653436323262323834333033306231643832393264373465
66303136306132393562313336313461303463613065366439646131373065326431326434343135
34623739376661356537376331323937303234613638396436313938613631343565313161303038
63376138396666386338666431306462386566656662626435363861333130343632383632373266
63643164303439323735343231353765363638373635313165393365333366333562643835666436
63323366346162333439393130373933383334383236663330623665376231666362623737366164
61356561336263336664343061363130346465643232396565313064663638383864306638316439
65343863653434313364666662376633643633356439353434333337643463356461303661353031
39353130633630653964613434343934386361393139646233643639353065306236616436363535
33313761346135383064306166613535333238633130613761653335633933343031
