$ANSIBLE_VAULT;1.1;AES256
34306561363234393037323536663436383466313139383338626639323166613635306432343338
6534333464646166366233633830303665663064656231330a393565663736306562356630656565
66303364626330643162646532633132383763623733396566303034633834323935376431633436
3830656266343735320a393362643066306136376432343063613732303839636632303963393036
62376539306365666632303333336162336466656331356632323461613965376235373439323330
33653237653638313939356662323065393234323763353830313264666330643635363361643738
34616539383931383134643030633066323166343632346637633936333931663439373731653531
61303434656133353461623435636361666666343338323737326562333932366538336532373134
38326436616366323232666130373066373664646536336331623038386437303430393463623138
30393464363237383865333335623931323164616232643538616563633231663135353465393664
626535633066323039316161373066373566
