keycloak_url: https://staging.ffxiv.id
passkey_relying_party_entity_name: FFXIV ID Staging
passkey_relying_party_id: staging.ffxiv.id

clients:
- client_id: netstone-api
  name: Netstone API
  description: Pseudo client for Netstone API. Login is not actually possible, this is currently only used for audience mapping.