keycloak_url: https://staging.ffxiv.id
passkey_relying_party_entity_name: FFXIV ID Staging
passkey_relying_party_id: staging.ffxiv.id

clients:
- client_id: monitoring
  name: Uptime Kuma
  description: Access to monitoring endpoints for Uptime Kuma.
  client_credentials_flow: true

- client_id: netstone-api
  name: Netstone API
  description: Pseudo client for Netstone API. Login is not actually possible, this is currently only used for audience mapping.

- client_id: alyx-discord
  name: Alyx Discord
  description: Alyx retrieves data from the Lodestone to create character sheets.
  client_credentials_flow: true
  jwks_url: https://alyx.staging.eorzea.online/.well-known/jwks
